integer(C_int), parameter :: sizeof_C_regex_t = 64_C_int
integer(C_int), parameter :: REG_EXTENDED = 1_C_int
integer(C_int), parameter :: REG_ICASE    = 2_C_int
integer(C_int), parameter :: REG_NEWLINE  = 4_C_int
integer(C_int), parameter :: REG_NOSUB    = 8_C_int
integer(C_int), parameter :: REG_NOTBOL = 1_C_int
integer(C_int), parameter :: REG_NOTEOL = 2_C_int
integer(C_int), parameter :: REG_NOMATCH = 1_C_int
